# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import openedx.core.djangoapps.xmodule_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPCoursePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', openedx.core.djangoapps.xmodule_django.models.CourseKeyField(db_index=True, max_length=255)),
                ('subscribe', models.IntegerField(choices=[(0, 'subscribe normal'), (1, 'subscribe pay')], default=0)),
            ],
        ),
    ]
