# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_vipcourseprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vippackage',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
