# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_vippackage_is_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viporder',
            name='openid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='viporder',
            name='os_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='viporder',
            name='outtradeno',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='viporder',
            name='receipt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viporder',
            name='refno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='viporder',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
