# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20181112_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipinfo',
            name='expired_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vipinfo',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='viporder',
            name='expired_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='viporder',
            name='start_at',
            field=models.DateTimeField(),
        ),
    ]
