# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20181113_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viporder',
            name='pay_type',
            field=models.IntegerField(choices=[(5, 'Balance'), (6, 'Offline'), (1, 'WeChat'), (2, 'Alipay'), (3, 'Union pay'), (4, 'Apple Pay')]),
        ),
    ]
