# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20181116_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipcourseenrollment',
            name='mode',
            field=models.CharField(default=b'audit', max_length=100),
        ),
    ]
