# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-19 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_vipcourseenrollment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='viporder',
            name='days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vippackage',
            name='days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viporder',
            name='pay_type',
            field=models.IntegerField(choices=[(5, 'Balance'), (6, 'Offline'), (1, 'WeChat'), (2, 'Alipay'), (3, 'Union pay'), (4, 'Apple Pay'), (7, 'Apple Inpurasing'), (8, 'WeChat App'), (9, 'WeChat H5'), (10, 'Alipay App')]),
        ),
    ]
