# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-17 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_auto_20190319_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vippackage',
            name='name',
            field=models.CharField(choices=[('1 Month', '1 Month'), ('3 Months', '3 Months'), ('6 Months', '6 Months'), ('12 Months', '12 Months'), ('24 Months', '24 Months')], max_length=64),
        ),
    ]
